Custom rerun failed tests and reportmerging
couchbaselabs/mobile-testkit pull request #1749
Opened 2020-09-18 20:43 UTC by mgcouchbase

#### Fixes #.

- [ ] Ran `flake8`
- [ ] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- 
-

2020-09-18 21:20 UTC, sridevi-15 requested changes
changes looks good, minor changes. Btw, all flake8 issues fixed, right? when I used xml parser in my local machine, it is having flake8 errors.
Also to make sure this works, can you provide jenkins successful run?

2020-09-18 21:20 UTC, sridevi-15 commented on utilities/xml_parser.py
> +                    failed_tests.append(tcname.split('[')[0])
remove the split for '['. We need to rerun with parameters that are failed, but not all

2020-09-18 21:20 UTC, sridevi-15 commented on utilities/xml_parser.py
> +    if failed_tests:
is this condition required as this is always be true. Though it is empty, it is still treated as true. May be you want to add the condtion that length of failed tests is more than 0

2020-09-18 21:20 UTC, sridevi-15 commented on utilities/xml_parser.py
> +    if passed_tests:
same as above

2020-09-21 17:46 UTC, euniceatcouchbase approved these changes

2020-09-21 17:46 UTC, euniceatcouchbase commented on utilities/xml_parser.py
> +                      action="store", dest="xml_file", default="http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-sgreplicate2/lastCompletedBuild/artifact/results/result
how about not setting default? or default location without job name, such as a regex pattern so each job can fill up with its name? just curious.

2020-09-30 18:16 UTC, sridevi-15 commented
@mgcouchbase , alreaddy reviewed last time itself, I think I requested for jenkins job which u provided now. Can you check jenkins results?
#1 and #3 jenkins url doing same, rerunning passed tests and merging the rerun url . one thing I noticed is that number of tests shows 47 total where as actual run shows 27. Looks like it is miscalculating . 
 I think what would be ideal is that have #1 to rerun with passed tests  and #3 with failed tests.  - that will help you to test your changes, #1 should still rerun with passed tests and should have failed tests in the results
#3 -  it should pass all the failed with rerun . Not sure why it shows failing in your jenkins run - in this case it should show all 27 tests passed, but only 4 tests ran. 

let me know if u want to sync up to test ur changes 

#2 is just a rerun passed or failed test which I guess u added for xml parser, but not for merging xml which is fine.

2020-10-07 06:20 UTC, sridevi-15 approved these changes

2020-10-07 06:21 UTC, merged