Adding params
couchbaselabs/mobile-testkit pull request #1793
Opened 2021-01-15 18:23 UTC by mgcouchbase

#### Fixes #.

- [ ] Ran `flake8`
- [ ] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- 
-

2021-01-19 06:24 UTC, sridevi-15 requested changes
need to  add start_prometheus change on SGW functional conftest file too

2021-01-19 06:25 UTC, sridevi-15 commented
Glad that you found a solution for prometheus ssl support

2021-01-19 18:01 UTC, euniceatcouchbase approved these changes

2021-01-19 21:20 UTC, mgcouchbase commented
> need to add start_prometheus change on SGW functional conftest file too..

it is already there
/topology_specific_tests/multiple_sync_gateways/conftest.py

2021-01-20 01:06 UTC, sridevi-15 approved these changes

2021-01-20 01:20 UTC, merged