Fix/custom port alternate address part2
couchbaselabs/mobile-testkit pull request #1831
Opened 2021-04-14 18:38 UTC by sridevi-15

#### Fixes #.

- [ ] Ran `flake8`
- [ ] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- custom port and alternate address  tests

2021-04-14 18:57 UTC, euniceatcouchbase requested changes

2021-04-14 18:57 UTC, euniceatcouchbase commented on keywords/couchbaseserver.py
> +        sdk_client = Bucket(connection_url, password='password')
this may need to be updated with sdk3 syntax once the sdk2>sdk3 PR merged to master

2021-04-14 18:57 UTC, euniceatcouchbase commented on keywords/couchbaseserver.py
> +        sdk_client = Bucket(connection_url, password='password')
reference this change in the PR: https://github.com/couchbaselabs/mobile-testkit/pull/1767/files#diff-00df9fc1cf3ee67d63285b3b2dd10825eee6ca5fc68255313f60675338b9fa3dR968

2021-04-15 01:12 UTC, mgcouchbase approved these changes

2021-04-15 03:47 UTC, euniceatcouchbase approved these changes

2021-04-15 17:38 UTC, merged