Feature/retry logic
couchbaselabs/mobile-testkit pull request #1840
Opened 2021-05-04 05:22 UTC by mgcouchbase

#### Fixes #.

- [ ] Ran `flake8`
- [ ] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- 
-

2021-05-18 00:07 UTC, euniceatcouchbase requested changes

2021-05-18 00:07 UTC, euniceatcouchbase commented on testsuites/CBLTester/p2p_tests/test_p2p_replication_filtering.py
> +                                       replication_type=replicator_type, endPointType=endpoint_type)
I think here is preparing the env and data, don't need to use replicator_type parameter. for instance, if replicator_type is pull, the docs created locally will never be able to be replicated to remote, the subsequence test logic will need to be changed.

2021-05-18 00:07 UTC, euniceatcouchbase commented on testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py
> +        assert expvars["syncgateway"]["per_db"][sg_db]["cbl_replication_pull"]["request_changes_count"] == 1, \
I guess you will need to resync with latest master for this file.

2021-05-18 02:24 UTC, sridevi-15 requested changes

2021-05-18 02:24 UTC, sridevi-15 commented on testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py
> +        assert expvars["syncgateway"]["per_db"][sg_db]["cbl_replication_pull"]["request_changes_count"] == 1, "request_changes_count did not get incremented "
just a minor one, no need to add space at the end of the string. Have it same as before. Previous one is right format

2021-05-18 02:24 UTC, sridevi-15 commented on testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py
> +    # sg_controller.restart_sync_gateways(cluster_config, url=sg_url)
remove this comment

2021-05-18 02:24 UTC, sridevi-15 commented on testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py
> +    replicator.stop(repl)
you need to add the assert Fail if exception is not caught, otherwise test passes thought expected exception is not caught

2021-05-18 02:24 UTC, sridevi-15 commented on testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py
> +    # Verify database doc counts
Suggestion : you can add steps as comments, which will be easy to go through the test which matches with the steps

2021-05-18 21:52 UTC, euniceatcouchbase approved these changes

2021-05-19 17:52 UTC, sridevi-15 approved these changes

2021-05-19 17:52 UTC, merged