Feature/attachment cleanup
couchbaselabs/mobile-testkit pull request #1899
Opened 2021-11-22 18:13 UTC by mgcouchbase

#### Fixes #.

- [ ] Ran `flake8`
- [ ] Ran `run_repo_tests.sh`

#### Changes proposed in this pull request:

- 
-

2021-12-04 00:31 UTC, euniceatcouchbase approved these changes

2021-12-04 06:01 UTC, sridevi-15 requested changes
did not review functional tests. You have matching steps and logic which should be good for now. 
Upgrade tests have few questions. 
Also upgrade tests with this branch is failing. Can you look both sgreplicate2 and upgrade tests?

2021-12-06 19:22 UTC, sridevi-15 commented
Also, Functional tests on mobile attachment are failing. Can you fix them?
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/3219/testReport/

2022-02-08 21:06 UTC, sridevi-15 commented
> Also, Functional tests on mobile attachment are failing. Can you fix them? http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/3219/testReport/
fixed

2022-02-08 21:06 UTC, sridevi-15 approved these changes

2022-02-08 21:37 UTC, euniceatcouchbase approved these changes

2022-02-08 21:39 UTC, merged